# Generated by Django 5.2.8 on 2025-11-25 22:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(auto_now_add=True)),
                ('systolic', models.PositiveSmallIntegerField(default=120)),
                ('diastolic', models.PositiveSmallIntegerField(default=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('grams', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Grams')),
                ('calories', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Calories')),
                ('protein', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='protein')),
                ('fat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Fat')),
                ('saturated_fat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Sat. Fat')),
                ('trans_fat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Trans Fat')),
                ('fibre', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Fibre')),
                ('sugar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Sugar')),
                ('carbs', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Carbs')),
                ('salt', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Salt')),
                ('sodium', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Sodium')),
                ('potassium', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Potassium')),
                ('magnesium', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Magnesium')),
                ('calcium', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Calcium')),
                ('iron', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Iron')),
                ('vitamin_D', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Vit. D')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracky.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracky.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracky.meal')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracky.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, verbose_name='Grams')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracky.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracky.recipe')),
            ],
        ),
    ]
