# Generated by Django 5.2.8 on 2025-11-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressure',
            name='heartrate',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
