# Generated by Django 5.2.8 on 2025-11-25 22:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0002_bloodpressure_heartrate_meal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealingredient',
            name='grams',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, verbose_name='Grams'),
        ),
    ]
