# Generated by Django 5.2.8 on 2025-11-25 22:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0003_mealingredient_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='grams',
            field=models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=10, verbose_name='Grams'),
        ),
    ]
