# Generated by Django 5.2.8 on 2025-11-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0004_alter_mealingredient_grams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealingredient',
            old_name='Ingredient',
            new_name='ingredient',
        ),
    ]
