# Generated by Django 5.2.8 on 2025-11-26 23:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0005_rename_ingredient_mealingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='grams',
            field=models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=10, verbose_name='Grams'),
        ),
    ]
