# Generated by Django 5.2.8 on 2025-11-28 00:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0006_alter_ingredient_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='grams',
            field=models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=10, verbose_name='Grams'),
        ),
    ]
