# Generated by Django 5.2.8 on 2025-11-28 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0007_alter_recipeingredient_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
