# Generated by Django 5.2.8 on 2025-12-01 02:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0008_alter_meal_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(default=django.utils.timezone.now)),
                ('lbs', models.PositiveSmallIntegerField(default=196)),
            ],
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
