# Generated by Django 5.2.8 on 2025-12-06 02:06

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0009_weight_alter_bloodpressure_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(choices=[('WR', 'WATER'), ('CF', 'COFFEE')], default='WR', max_length=2)),
                ('litres', models.DecimalField(decimal_places=4, default=Decimal('300'), max_digits=10, verbose_name='Litres')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodium',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Sodium (not from NaCl)'),
        ),
    ]
