# Generated by Django 5.2.8 on 2025-12-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0010_drink_alter_ingredient_sodium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink',
            field=models.CharField(choices=[('WR', 'Water'), ('CF', 'Coffee')], default='WR', max_length=2),
        ),
    ]
