# Generated by Django 5.2.8 on 2025-12-06 17:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0011_alter_drink_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='litres',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.299999999999999988897769753748434595763683319091796875'), max_digits=10, verbose_name='Litres'),
        ),
    ]
