# Generated by Django 5.2.8 on 2025-12-07 02:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0012_alter_drink_litres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink',
            field=models.CharField(choices=[('WR', 'Water'), ('CF', 'Coffee'), ('CO', 'Coco'), ('CC', 'CoffeeCoco'), ('TE', 'Tea')], default='WR', max_length=2),
        ),
        migrations.AlterField(
            model_name='drink',
            name='litres',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, verbose_name='Litres'),
        ),
    ]
