# Generated by Django 5.2.8 on 2025-12-08 14:19

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0014_mood_sleep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(default=django.utils.timezone.now)),
                ('grams', models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=10, verbose_name='Grams')),
            ],
        ),
    ]
