# Generated by Django 5.2.8 on 2025-12-09 02:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0016_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='protein',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='protein'),
        ),
    ]
