# Generated by Django 5.2.8 on 2025-12-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracky', '0017_remove_ingredient_protien_ingredient_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise',
            field=models.CharField(choices=[('CY', 'Cycle'), ('HK', 'Hike')], default='CY', max_length=2),
        ),
    ]
